# Generated by Django 4.0.5 on 2022-06-17 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web01', '0003_prettynum_alter_userinfo_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prettynum',
            name='status',
            field=models.SmallIntegerField(choices=[(1, '已经占用'), (2, '未占用')], default=2, verbose_name='状态'),
        ),
    ]
